random-nicks:
  - Gandalf07Yt
  - TheProPvP2006
  - Gamur750
  - DopiesJosestar
  - GnomeQuangourou7645
  - SnfzxwasO
  - nQeoLaID
  - Agent 007
  - Alinéa
  - Gruty
  - xXSerpentXx
  - Potaaato
  - Frexs
  - Meyriu
  - PetiteFée
  - Pewfan
  - Rocketman
  - Ectobiologiste
  - Felipero
  - Gruty
  - MaigezzBienCuite
  - Seltade
  - Kairrin
  - Cristobal
  - ItsGodHere
  - RainbowMan
  - JteFaitFlyEnF5
  - WeshTuEtNul
  - Pewfan
  - GeoMan
  - Multi-Prise
  - _odst44_
  - Titou
  - ChasseurDeFantome
  - PiocheUneCarte
  - PingouinBourré
  - Kamasoutra
  - MaTerre
  - semyz
  - NoSmoking
  - Vodomores
  - GodOfDark
  - Ralice
  - FritesAuFour
  - Tko20
  - CasquetteNike
  - Jegudiel
  - LawMarshall
  - 1franc
  - fiesta_red
  - mcink please
  - The_Professor2
  - Allyria
  - iMentalink
  - FreeRevolution
  - Chocookie
  - PorteRoulante
  - mew89
  - D4rkSky
  - Loes
  - RiccoRodriguez
  - PsykaPsyka
  - TheBeginning
  - Barzotti
  - Dianobol
  - ouragan78
  - BrokenBells
  - Skyler-Style
  - ColombeBlanche
  - ThomasCarglass
  - Cislashack
  - THExSTONE
  - AltEspaceAltGr
  - BlueHand
  - CarglasSexuel
  - HospitalGiant
  - PWehpweh
  - FeutreJaune
  - JauneNeon
  - Shadowbear
  - Juntaho
  - UJelly
  - SmokeThisWeed
  - Strazcrips
  - RaymondArcher

reset-pseudonyme: "§a§l»§r§f Vous êtes revenue sur votre apparence normal."
reset-nametag: "§7[§e...§7]"
random-nametag: "§7[§e...§7]"
Title: "Nick"
Content: "§a§l»§r§f Veuillez séléctionner une options."
Boutton-Fermer: "§cFermer"
Activer: "Activer"
Desactiver: "Désactiver"
nick-message: "§a§l»§r§f Vous êtes désormais sous le pseudonyme : §a{nick}§f !"


